/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEquipamentosIndexRouteImport } from './routes/_authenticated/equipamentos.index'
import { Route as AuthenticatedEquipamentosIdRouteImport } from './routes/_authenticated/equipamentos.$id'
import { Route as AuthenticatedEquipamentosIdManutencaoRouteImport } from './routes/_authenticated/equipamentos.$id.manutencao'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipamentosIndexRoute =
  AuthenticatedEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIdRoute =
  AuthenticatedEquipamentosIdRouteImport.update({
    id: '/equipamentos/$id',
    path: '/equipamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIdManutencaoRoute =
  AuthenticatedEquipamentosIdManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/equipamentos': typeof AuthenticatedEquipamentosIndexRoute
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/_authenticated/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/_authenticated/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/equipamentos/$id'
    | '/equipamentos/'
    | '/equipamentos/$id/manutencao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/equipamentos/$id'
    | '/equipamentos'
    | '/equipamentos/$id/manutencao'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/equipamentos/$id'
    | '/_authenticated/equipamentos/'
    | '/_authenticated/equipamentos/$id/manutencao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/': {
      id: '/_authenticated/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/$id': {
      id: '/_authenticated/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/$id/manutencao': {
      id: '/_authenticated/equipamentos/$id/manutencao'
      path: '/manutencao'
      fullPath: '/equipamentos/$id/manutencao'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdManutencaoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
  }
}

interface AuthenticatedEquipamentosIdRouteChildren {
  AuthenticatedEquipamentosIdManutencaoRoute: typeof AuthenticatedEquipamentosIdManutencaoRoute
}

const AuthenticatedEquipamentosIdRouteChildren: AuthenticatedEquipamentosIdRouteChildren =
  {
    AuthenticatedEquipamentosIdManutencaoRoute:
      AuthenticatedEquipamentosIdManutencaoRoute,
  }

const AuthenticatedEquipamentosIdRouteWithChildren =
  AuthenticatedEquipamentosIdRoute._addFileChildren(
    AuthenticatedEquipamentosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedEquipamentosIdRoute: typeof AuthenticatedEquipamentosIdRouteWithChildren
  AuthenticatedEquipamentosIndexRoute: typeof AuthenticatedEquipamentosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedEquipamentosIdRoute:
    AuthenticatedEquipamentosIdRouteWithChildren,
  AuthenticatedEquipamentosIndexRoute: AuthenticatedEquipamentosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
