/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedCotacoesRouteImport } from './routes/_authenticated/cotacoes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedNotasFiscaisIndexRouteImport } from './routes/_authenticated/notas-fiscais.index'
import { Route as AuthenticatedEquipamentosIndexRouteImport } from './routes/_authenticated/equipamentos.index'
import { Route as AuthenticatedCustosIndexRouteImport } from './routes/_authenticated/custos.index'
import { Route as AuthenticatedCotacoesIndexRouteImport } from './routes/_authenticated/cotacoes.index'
import { Route as AuthenticatedEquipamentosIdRouteImport } from './routes/_authenticated/equipamentos.$id'
import { Route as AuthenticatedNotasFiscaisIdIndexRouteImport } from './routes/_authenticated/notas-fiscais.$id.index'
import { Route as AuthenticatedEquipamentosIdIndexRouteImport } from './routes/_authenticated/equipamentos.$id.index'
import { Route as AuthenticatedCotacoesIdIndexRouteImport } from './routes/_authenticated/cotacoes.$id.index'
import { Route as AuthenticatedEquipamentosIdManutencaoRouteImport } from './routes/_authenticated/equipamentos.$id.manutencao'
import { Route as AuthenticatedEquipamentosIdHistoricoRouteImport } from './routes/_authenticated/equipamentos.$id.historico'
import { Route as AuthenticatedEquipamentosIdHistoricoHistIdRouteImport } from './routes/_authenticated/equipamentos.$id.historico.$histId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCotacoesRoute = AuthenticatedCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasFiscaisIndexRoute =
  AuthenticatedNotasFiscaisIndexRouteImport.update({
    id: '/notas-fiscais/',
    path: '/notas-fiscais/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIndexRoute =
  AuthenticatedEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustosIndexRoute =
  AuthenticatedCustosIndexRouteImport.update({
    id: '/custos/',
    path: '/custos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCotacoesIndexRoute =
  AuthenticatedCotacoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCotacoesRoute,
  } as any)
const AuthenticatedEquipamentosIdRoute =
  AuthenticatedEquipamentosIdRouteImport.update({
    id: '/equipamentos/$id',
    path: '/equipamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotasFiscaisIdIndexRoute =
  AuthenticatedNotasFiscaisIdIndexRouteImport.update({
    id: '/notas-fiscais/$id/',
    path: '/notas-fiscais/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIdIndexRoute =
  AuthenticatedEquipamentosIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedCotacoesIdIndexRoute =
  AuthenticatedCotacoesIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedCotacoesRoute,
  } as any)
const AuthenticatedEquipamentosIdManutencaoRoute =
  AuthenticatedEquipamentosIdManutencaoRouteImport.update({
    id: '/manutencao',
    path: '/manutencao',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedEquipamentosIdHistoricoRoute =
  AuthenticatedEquipamentosIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => AuthenticatedEquipamentosIdRoute,
  } as any)
const AuthenticatedEquipamentosIdHistoricoHistIdRoute =
  AuthenticatedEquipamentosIdHistoricoHistIdRouteImport.update({
    id: '/$histId',
    path: '/$histId',
    getParentRoute: () => AuthenticatedEquipamentosIdHistoricoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cotacoes': typeof AuthenticatedCotacoesRouteWithChildren
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
  '/custos/': typeof AuthenticatedCustosIndexRoute
  '/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/notas-fiscais/': typeof AuthenticatedNotasFiscaisIndexRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/cotacoes/$id/': typeof AuthenticatedCotacoesIdIndexRoute
  '/equipamentos/$id/': typeof AuthenticatedEquipamentosIdIndexRoute
  '/notas-fiscais/$id/': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cotacoes': typeof AuthenticatedCotacoesIndexRoute
  '/custos': typeof AuthenticatedCustosIndexRoute
  '/equipamentos': typeof AuthenticatedEquipamentosIndexRoute
  '/notas-fiscais': typeof AuthenticatedNotasFiscaisIndexRoute
  '/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/cotacoes/$id': typeof AuthenticatedCotacoesIdIndexRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdIndexRoute
  '/notas-fiscais/$id': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cotacoes': typeof AuthenticatedCotacoesRouteWithChildren
  '/_authenticated/equipamentos/$id': typeof AuthenticatedEquipamentosIdRouteWithChildren
  '/_authenticated/cotacoes/': typeof AuthenticatedCotacoesIndexRoute
  '/_authenticated/custos/': typeof AuthenticatedCustosIndexRoute
  '/_authenticated/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/_authenticated/notas-fiscais/': typeof AuthenticatedNotasFiscaisIndexRoute
  '/_authenticated/equipamentos/$id/historico': typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  '/_authenticated/equipamentos/$id/manutencao': typeof AuthenticatedEquipamentosIdManutencaoRoute
  '/_authenticated/cotacoes/$id/': typeof AuthenticatedCotacoesIdIndexRoute
  '/_authenticated/equipamentos/$id/': typeof AuthenticatedEquipamentosIdIndexRoute
  '/_authenticated/notas-fiscais/$id/': typeof AuthenticatedNotasFiscaisIdIndexRoute
  '/_authenticated/equipamentos/$id/historico/$histId': typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cotacoes'
    | '/equipamentos/$id'
    | '/cotacoes/'
    | '/custos/'
    | '/equipamentos/'
    | '/notas-fiscais/'
    | '/equipamentos/$id/historico'
    | '/equipamentos/$id/manutencao'
    | '/cotacoes/$id/'
    | '/equipamentos/$id/'
    | '/notas-fiscais/$id/'
    | '/equipamentos/$id/historico/$histId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/cotacoes'
    | '/custos'
    | '/equipamentos'
    | '/notas-fiscais'
    | '/equipamentos/$id/historico'
    | '/equipamentos/$id/manutencao'
    | '/cotacoes/$id'
    | '/equipamentos/$id'
    | '/notas-fiscais/$id'
    | '/equipamentos/$id/historico/$histId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cotacoes'
    | '/_authenticated/equipamentos/$id'
    | '/_authenticated/cotacoes/'
    | '/_authenticated/custos/'
    | '/_authenticated/equipamentos/'
    | '/_authenticated/notas-fiscais/'
    | '/_authenticated/equipamentos/$id/historico'
    | '/_authenticated/equipamentos/$id/manutencao'
    | '/_authenticated/cotacoes/$id/'
    | '/_authenticated/equipamentos/$id/'
    | '/_authenticated/notas-fiscais/$id/'
    | '/_authenticated/equipamentos/$id/historico/$histId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cotacoes': {
      id: '/_authenticated/cotacoes'
      path: '/cotacoes'
      fullPath: '/cotacoes'
      preLoaderRoute: typeof AuthenticatedCotacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais/': {
      id: '/_authenticated/notas-fiscais/'
      path: '/notas-fiscais'
      fullPath: '/notas-fiscais/'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/': {
      id: '/_authenticated/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos/': {
      id: '/_authenticated/custos/'
      path: '/custos'
      fullPath: '/custos/'
      preLoaderRoute: typeof AuthenticatedCustosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cotacoes/': {
      id: '/_authenticated/cotacoes/'
      path: '/'
      fullPath: '/cotacoes/'
      preLoaderRoute: typeof AuthenticatedCotacoesIndexRouteImport
      parentRoute: typeof AuthenticatedCotacoesRoute
    }
    '/_authenticated/equipamentos/$id': {
      id: '/_authenticated/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas-fiscais/$id/': {
      id: '/_authenticated/notas-fiscais/$id/'
      path: '/notas-fiscais/$id'
      fullPath: '/notas-fiscais/$id/'
      preLoaderRoute: typeof AuthenticatedNotasFiscaisIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/$id/': {
      id: '/_authenticated/equipamentos/$id/'
      path: '/'
      fullPath: '/equipamentos/$id/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdIndexRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/cotacoes/$id/': {
      id: '/_authenticated/cotacoes/$id/'
      path: '/$id'
      fullPath: '/cotacoes/$id/'
      preLoaderRoute: typeof AuthenticatedCotacoesIdIndexRouteImport
      parentRoute: typeof AuthenticatedCotacoesRoute
    }
    '/_authenticated/equipamentos/$id/manutencao': {
      id: '/_authenticated/equipamentos/$id/manutencao'
      path: '/manutencao'
      fullPath: '/equipamentos/$id/manutencao'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdManutencaoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/equipamentos/$id/historico': {
      id: '/_authenticated/equipamentos/$id/historico'
      path: '/historico'
      fullPath: '/equipamentos/$id/historico'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdHistoricoRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdRoute
    }
    '/_authenticated/equipamentos/$id/historico/$histId': {
      id: '/_authenticated/equipamentos/$id/historico/$histId'
      path: '/$histId'
      fullPath: '/equipamentos/$id/historico/$histId'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdHistoricoHistIdRouteImport
      parentRoute: typeof AuthenticatedEquipamentosIdHistoricoRoute
    }
  }
}

interface AuthenticatedCotacoesRouteChildren {
  AuthenticatedCotacoesIndexRoute: typeof AuthenticatedCotacoesIndexRoute
  AuthenticatedCotacoesIdIndexRoute: typeof AuthenticatedCotacoesIdIndexRoute
}

const AuthenticatedCotacoesRouteChildren: AuthenticatedCotacoesRouteChildren = {
  AuthenticatedCotacoesIndexRoute: AuthenticatedCotacoesIndexRoute,
  AuthenticatedCotacoesIdIndexRoute: AuthenticatedCotacoesIdIndexRoute,
}

const AuthenticatedCotacoesRouteWithChildren =
  AuthenticatedCotacoesRoute._addFileChildren(
    AuthenticatedCotacoesRouteChildren,
  )

interface AuthenticatedEquipamentosIdHistoricoRouteChildren {
  AuthenticatedEquipamentosIdHistoricoHistIdRoute: typeof AuthenticatedEquipamentosIdHistoricoHistIdRoute
}

const AuthenticatedEquipamentosIdHistoricoRouteChildren: AuthenticatedEquipamentosIdHistoricoRouteChildren =
  {
    AuthenticatedEquipamentosIdHistoricoHistIdRoute:
      AuthenticatedEquipamentosIdHistoricoHistIdRoute,
  }

const AuthenticatedEquipamentosIdHistoricoRouteWithChildren =
  AuthenticatedEquipamentosIdHistoricoRoute._addFileChildren(
    AuthenticatedEquipamentosIdHistoricoRouteChildren,
  )

interface AuthenticatedEquipamentosIdRouteChildren {
  AuthenticatedEquipamentosIdHistoricoRoute: typeof AuthenticatedEquipamentosIdHistoricoRouteWithChildren
  AuthenticatedEquipamentosIdManutencaoRoute: typeof AuthenticatedEquipamentosIdManutencaoRoute
  AuthenticatedEquipamentosIdIndexRoute: typeof AuthenticatedEquipamentosIdIndexRoute
}

const AuthenticatedEquipamentosIdRouteChildren: AuthenticatedEquipamentosIdRouteChildren =
  {
    AuthenticatedEquipamentosIdHistoricoRoute:
      AuthenticatedEquipamentosIdHistoricoRouteWithChildren,
    AuthenticatedEquipamentosIdManutencaoRoute:
      AuthenticatedEquipamentosIdManutencaoRoute,
    AuthenticatedEquipamentosIdIndexRoute:
      AuthenticatedEquipamentosIdIndexRoute,
  }

const AuthenticatedEquipamentosIdRouteWithChildren =
  AuthenticatedEquipamentosIdRoute._addFileChildren(
    AuthenticatedEquipamentosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCotacoesRoute: typeof AuthenticatedCotacoesRouteWithChildren
  AuthenticatedEquipamentosIdRoute: typeof AuthenticatedEquipamentosIdRouteWithChildren
  AuthenticatedCustosIndexRoute: typeof AuthenticatedCustosIndexRoute
  AuthenticatedEquipamentosIndexRoute: typeof AuthenticatedEquipamentosIndexRoute
  AuthenticatedNotasFiscaisIndexRoute: typeof AuthenticatedNotasFiscaisIndexRoute
  AuthenticatedNotasFiscaisIdIndexRoute: typeof AuthenticatedNotasFiscaisIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCotacoesRoute: AuthenticatedCotacoesRouteWithChildren,
  AuthenticatedEquipamentosIdRoute:
    AuthenticatedEquipamentosIdRouteWithChildren,
  AuthenticatedCustosIndexRoute: AuthenticatedCustosIndexRoute,
  AuthenticatedEquipamentosIndexRoute: AuthenticatedEquipamentosIndexRoute,
  AuthenticatedNotasFiscaisIndexRoute: AuthenticatedNotasFiscaisIndexRoute,
  AuthenticatedNotasFiscaisIdIndexRoute: AuthenticatedNotasFiscaisIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
